//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCource_ProjectFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KPEntities : DbContext
    {
        private static KPEntities context;
        public KPEntities()
            : base("name=KPEntities")
        {
        }

        public static KPEntities GetContext()
        {
            if (context == null) return context = new KPEntities();
            else return context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Авторы> Авторы { get; set; }
        public virtual DbSet<Выдача_книг> Выдача_книг { get; set; }
        public virtual DbSet<Книги> Книги { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Читатели> Читатели { get; set; }
    }
}
