//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCource_ProjectFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выдача_книг
    {
        public int Номер_выдачи { get; set; }
        public int Номер_читателя { get; set; }
        public int Номер_книги { get; set; }
        public System.DateTime Дача_выдачи { get; set; }
        public System.DateTime Дата_сдачи { get; set; }
        public int Номер_сотрудника { get; set; }
    
        public virtual Книги Книги { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Читатели Читатели { get; set; }
    }
}
