//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCource_ProjectFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Книги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Книги()
        {
            this.Выдача_книг = new HashSet<Выдача_книг>();
        }
    
        public int Номер_книги { get; set; }
        public string Название_книги { get; set; }
        public string Издательство { get; set; }
        public string Тематика_книги { get; set; }
        public System.DateTime Дата_выхода { get; set; }
        public Nullable<int> Номер_автора { get; set; }
        public Nullable<int> Кол_книг { get; set; }
    
        public virtual Авторы Авторы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выдача_книг> Выдача_книг { get; set; }
    }
}
